### ISSUE TITLE
Using Kube-no-trouble in windows OS

### ISSUE THREAD

**Issue by gerardgorrion** [doitintl/kube-no-trouble#108]
Good morning, 

There're some way to use kubent into windows OS system?
unfortunadle, I use windows to work with kubernetes clusters and we want to upgrade our clusters to 1.16 and need some way to use kubent to locate used deprecated API versions in 1.16.

Good job and thanks!, regards.

**Comment by david-doit-intl** [comment]
My advice is to build it for windows. I will see about building it for windows automatically but windows is generally more painful to support than mac or linux. We do offer a dockerfile, so you could use that as well.

**Comment by david-doit-intl** [comment]
@gerardgorrion cross compile seems to work ok. So we will be releasing a windows binary see https://github.com/doitintl/kube-no-trouble/pull/110

**Comment by gerardgorrion** [comment]
@david-doit-intl thanks a lot!
How it works binary files? same deployment procedure?

**Comment by david-doit-intl** [comment]
Yes should be, we just need a windows machine to test it.

**Comment by stepanstipl** [comment]
Hi @gerardgorrion, so this is out (finally 😉 ), you can download the latest [0.4.0 release](https://github.com/doitintl/kube-no-trouble/releases/tag/0.4.0). It has a Windows binary published. THe install is manual - i.e. download and unpack for now, we should document this better #131, and/or automate in future.

Give it a go and let us know if there are any issues! Thanks 👍

**Comment by gerardgorrion** [comment]
Hi @stepanstipl  thank you so much, window's version works fine!

We updated the clusters some weeks ago but the next users with same problem will be able to use it.

Regards and good job!
