### ISSUE TITLE
Detect K8s version and suggest only relevant issues

### ISSUE THREAD

**Issue by stepanstipl** [doitintl/kube-no-trouble#130]
We can try to detect a version of the cluster a user is running and suggest only updates relevant for the existing/next minor version, since we have info on since what version are the replacement resources available.

I.e. if user runs 1.15, and is dealing with upgrade to 1.16, no point flagging deprecation in 1.22 that are only available for replacement in 1.18.

**Comment by stepanstipl** [comment]
Some details on how this should work:
- Only detect version if one of the relevant collectors (cluster, Helm v2/3) is enabled _(I'm thinking about extending the collector interface here)_
- Allow version override via flag - for cases when this is used with files in CI
- By default filter findings to the relevant ones only, i.e. if it's possible to upgrade (and we have that info)
  - Q1: Should we filter based on the current cluster version or the next minor - assuming the typical scenario is to use this tool when upgrading clusters. I.e:
    a) `result.Since <= masterMinorVersion`
    b) `result.Since <= masterMinorVersion + 1`
    In b) case you won't be able to fix this until after the upgrade, so seems like a) might make more sense? Downside potentially missing some issues, although this should never happen in practice, as replacement versions are first introduced and old ones removed only after.
  - Q2: What to do about resources being removed, without replacement? I don't think we have this well covered. I'm thinking just warn about those - `Since` will be probably when the resource was marked as deprecated in this case, so we might warn a bit early, but better than late ;).
- Add flag to disable any filtering and display all


@david-doit-intl any thoughts?

**Comment by david-doit-intl** [comment]
1) We should check on the next minor yes :+1: , should have a flag to check up to latest perhaps.
2) We should defo warn about things being removed!
