### ISSUE TITLE
Add support for krew plugin

### ISSUE THREAD

**Issue by ghost** [doitintl/kube-no-trouble#133]
https://github.com/kubernetes-sigs/krew

**Comment by stepanstipl** [comment]
This is an interesting idea, but we're not a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) atm. Maybe that's something worth exploring, not sure what are the implications and/or benefits. For one though you have to distribute the binary as `kubectl-<commnad>`.

**Comment by david-doit-intl** [comment]
Yeah its something to think about.

**Comment by david-doit-intl** [comment]
It wouldn't be that hard to distribute an extra binary as kubectl-<kubent>
