### ISSUE TITLE
Native support for CustomResourceDefinition

### ISSUE THREAD

**Issue by sherifkayad** [doitintl/kube-no-trouble#176]
First of all thanks a lot for this nice utility. 

## Problem Statement
I was just wandering why the `CustomResourceDefinition` object **isn't natively supported**. So basically if I have something like:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mystuff.crd.k8s.myorga.com
spec:
  group: crd.k8s.myorga.com
  names:
    kind: MyStuff
...
```
Attempting to apply the following to a cluster with a recent version of k8s e.g. 1.20 I get a message like:
```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

That being said, running `kubent` doesn't print out this object at all.

## Proposed Solution
I would love to see a native support for the CRD definition object itself (`CustomResourceDefinition`) similar to other k8s objects like `Ingress`, `ClusterRole`, `Service`, .. etc.

## Current Workaround
The current workaround is to use the `-a` flag of `kubent` e.g.:
```bash
$  kubent -a CustomResourceDefinition.v1beta1.apiextensions.k8s.io 
```
In such case I get:
```
4:17PM INF >>> Kube No Trouble `kubent` <<<
4:17PM INF version 0.4.0 (git sha 3d82a3f0714c97035c27374854703256b3d69125)
4:17PM INF Initializing collectors and retrieving data
4:17PM INF Retrieved 207 resources from collector name=Cluster
4:17PM INF Retrieved 0 resources from collector name="Helm v2"
4:17PM INF Retrieved 266 resources from collector name="Helm v3"
4:17PM INF Loaded ruleset name=custom.rego.tmpl
4:17PM INF Loaded ruleset name=deprecated-1-16.rego
4:17PM INF Loaded ruleset name=deprecated-1-22.rego
__________________________________________________________________________________________
>>> Additional resources (custom) <<<
------------------------------------------------------------------------------------------
KIND                       NAMESPACE     NAME                                         API_VERSION                    REPLACE_WITH (SINCE)
CustomResourceDefinition   <undefined>   mystuff.crd.k8s.myorga.com             apiextensions.k8s.io/v1beta1           <na> (<na>+)
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.22 <<<
------------------------------------------------------------------------------------------
KIND      NAMESPACE     NAME                     API_VERSION          REPLACE_WITH (SINCE)
Ingress   kube-system   ingress-kube-dashboard   extensions/v1beta1   networking.k8s.io/v1beta1 (1.14+)
Ingress   kube-system   ingress-master           extensions/v1beta1   networking.k8s.io/v1beta1 (1.14+)
```

**Comment by sherifkayad** [comment]
@stepanstipl amazing stuff! Thanks for the prompt reply. The nightly looks definitely promising and delivering now as expected. I can see a lot of more objects now not only including CRDs but also `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration` 😃 

Should we wait for the release to close this one here or what do you think?

**Comment by stepanstipl** [comment]
Yep, that was the plan, close once this is in a release. Thanks for letting us know this is working 👍 🎉  and if you're happy & tested it in nightly, feel free to close the issue 😉

**Comment by sherifkayad** [comment]
@stepanstipl will close this one and keep an eye for the upcoming stable release
