### ISSUE TITLE
Does not detect the deprecation of ingress networking.k8s.io/v1beta1

### ISSUE THREAD

**Issue by fredgate** [doitintl/kube-no-trouble#200]
I am testing `kubent` with a Helm chart that contains 4 resources including one ingress in a deprecated version against k8s 1.22.

Here is the output of my Helm chart :
```
helm template my-chart
...
# Source: my-chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
...
```

But when I run `kubent` against this chart, it find no deprecations :
```
helm template my-chart | kubent --cluster=false --helm2=false --helm3=false -o json -f -
5:39PM INF >>> Kube No Trouble `kubent` <<<
5:39PM INF version 0.4.0 (git sha 3d82a3f0714c97035c27374854703256b3d69125)
5:39PM INF Initializing collectors and retrieving data
5:39PM INF Retrieved 4 resources from collector name=File
5:39PM INF Loaded ruleset name=custom.rego.tmpl
5:39PM INF Loaded ruleset name=deprecated-1-16.rego
5:39PM INF Loaded ruleset name=deprecated-1-22.rego
[]
```

It seems to me to be an error according to this documentation https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Comment by stepanstipl** [comment]
Hi @fredgate can you please try this with the latest [0.5.0 release](https://github.com/doitintl/kube-no-trouble/releases/tag/0.5.0). Most of the 1.22/125 resources have only been added recently.

**Comment by balasu** [comment]
Hi i tried it, not getting any result. its 0.5.0 and k8s is 1.22.0
![image](https://user-images.githubusercontent.com/39425180/129455522-1c93d73e-5afb-4372-86d7-4fa12910f3df.png)

**Comment by fredgate** [comment]
Sorry for the response time, I was on vacation.
I just tested with kubent 0.5.0 and it worked:
```
3:52PM INF >>> Kube No Trouble `kubent` <<<
3:52PM INF version 0.5.0 (git sha e8065c4aaa20a57033684e63f40a0e6f44add6f4)
3:52PM INF Initializing collectors and retrieving data
3:52PM INF Retrieved 4 resources from collector name=File
3:52PM INF Loaded ruleset name=custom.rego.tmpl
3:52PM INF Loaded ruleset name=deprecated-1-16.rego
3:52PM INF Loaded ruleset name=deprecated-1-22.rego
3:52PM INF Loaded ruleset name=deprecated-1-25.rego
[
        {
                "Name": "cdn",
                "Namespace": "\u003cundefined\u003e",
                "Kind": "Ingress",
                "ApiVersion": "networking.k8s.io/v1beta1",
                "RuleSet": "Deprecated APIs removed in 1.22",
                "ReplaceWith": "networking.k8s.io/v1",
                "Since": {}
        }
]
```

**Comment by balasu** [comment]
Hi @fredgate could it possible to help me, i m trying directly on the cluster

**Comment by fredgate** [comment]
I didn't try by collecting resources from cluster, but by collecting them from a file (or input stream which is the same).
May be you could try to test an specific resource (like ingress) by exporting it from cluster like :
`kubectl get ingress <your-ingress> -o yaml | kubent --cluster=false --helm2=false --helm3=false -o json -f -`

**Comment by stepanstipl** [comment]
@fredgate thanks for trying and confirming this works now. 👍 🎉 

@balasu based on your screenshot, I can see the tool detected 5 relevant resources to check in your cluster. Can you please share the one(s) you would expect to be flagged as deprecated? I simple output of  `kubectl get [resource_type] [resource_name] --output yaml` would do.

**Comment by balasu** [comment]
Hi
pl find the atatched 
![image](https://user-images.githubusercontent.com/39425180/129606509-313e3fe8-050f-4151-a236-4c04848850c1.png)

**Comment by fredgate** [comment]
@balasu Your ingress uses the new API so it is normal that `kubent` does not detect some deprecation. Your are up to date.

**Comment by stepanstipl** [comment]
Yep, @balasu  if you look at the `kubectl.kubernetes.io/last-applied-configuration` annotation of your resource, it contains `"apiVersion":"networking.k8s.io/v1"`, which means this resource was created using the new `v1` version of the networking API. And as such, it's not problematic, and not expected to be flagged by kubent.
