### ISSUE TITLE
Add docs about running on all manifests in a directory

### ISSUE THREAD

**Issue by hamtaai** [doitintl/kube-no-trouble#211]
Hi!

Building on https://github.com/doitintl/kube-no-trouble/pull/15, would it be possible to add a directory collector? 

E.g. `kubent -d my_folder` would recursively collect resources from my_folder.

Would help to replace `kubent -f <a lot of files from the same folder>`.

**Comment by stepanstipl** [comment]
Hi @hamtaai, thanks - this is definitely a valid use case. I would like to support it, however, I feel this should be possible to accomplish via bash expansion. I've tried this and it seems to work:
```bash
FILES=($(ls *.yaml)); kubent ${FILES[@]/#/-f} --helm2=false --helm3=false -c=false
```

Let me know if that works for your use case? (I would lie to add this to docs in case someone else needs this in the future).

**Comment by mhavelant** [comment]
Hey,

hamtaai here from my other account - I solved my original issue with some bash script back then (although it was not an elegant one-liner). 

Adding that snippet to the docs would be great, in any case, thanks! And maybe some time in the future it can be replaced by a `kubent`-native solution.
