### ISSUE TITLE
kubent doesn't  output  resource deprecate information in our own namespace .

### ISSUE THREAD

**Issue by victorchen2022** [doitintl/kube-no-trouble#255]
I have other namespace that has deprecated api version, but it does't show._
_________________________________________________________________________________________
>>> Deprecated APIs removed in 1.16 <<<
------------------------------------------------------------------------------------------
KIND         NAMESPACE     NAME                              API_VERSION          REPLACE_WITH (SINCE)
Deployment   kube-system   metrics-server                    extensions/v1beta1   apps/v1 (1.9.0)
Deployment   monitoring    prometheus-alertmanager           extensions/v1beta1   apps/v1 (1.9.0)
Deployment   kube-system   aliyun-acr-credential-helper      apps/v1beta2         apps/v1 (1.9.0)
Deployment   kube-system   alicloud-application-controller   extensions/v1beta1   apps/v1 (1.9.0)
Deployment   monitoring    prometheus-kube-state-metrics     extensions/v1beta1   apps/v1 (1.9.0)
Deployment   monitoring    prometheus-pushgateway            extensions/v1beta1   apps/v1 (1.9.0)
Deployment   kube-system   alicloud-disk-controller          extensions/v1beta1   apps/v1 (1.9.0)
Deployment   kube-system   alicloud-monitor-controller       extensions/v1beta1   apps/v1 (1.9.0)
Deployment   monitoring    prometheus-server                 extensions/v1beta1   apps/v1 (1.9.0)
DaemonSet    kube-system   kube-flannel-ds                   extensions/v1beta1   apps/v1 (1.9.0)
DaemonSet    kube-system   flexvolume                        extensions/v1beta1   apps/v1 (1.9.0)
DaemonSet    monitoring    prometheus-node-exporter          extensions/v1beta1   apps/v1 (1.9.0)

**Comment by stepanstipl** [comment]
Hi @victorchen2022,
- can you please post full manifest of one of the resources that you would expect to be detected? I.e. `kubectl get [KIND] [NAME] -n [NAMESPACE] -o yaml`
- and how are your resources deployed, e.g. using `kubectl`, Helm, or something else?

**Comment by stepanstipl** [comment]
Haven't heard back.
