### ISSUE TITLE
Add a version command

### ISSUE THREAD

**Issue by Skaronator** [doitintl/kube-no-trouble#259]
Hi,

would it be possible to add a `kubent --version` or `kubent version` command to check the current version?

I'd like to use that command to verify that the installation was correctly. Currently, when running `kubent version` it'll start `kubent` without any error or waning :D

**Comment by dark0dave** [comment]
When you kubent is run the version is printed at the info level:

```
	log.Info().Msg(">>> Kube No Trouble `kubent` <<<")
	log.Info().Msgf("version %s (git sha %s)", version, gitSha)
```
This should be possible to see by setting the flag for logging to the info level.

**Comment by dark0dave** [comment]
We could consider adding a version flag, such as:
```
kubent --version
```
however currently the config from the flags is passed directly to the collectors, so its currently not possible to run kubent and just get the version.
