### ISSUE TITLE
Ingress `extensions/v1beta1` is seen as `networking.k8s.io/v1beta1` instead

### ISSUE THREAD

**Issue by Berber31** [doitintl/kube-no-trouble#261]
**Describe the bug**
Ingress `extensions/v1beta1` is seen as `networking.k8s.io/v1beta1` instead

**To Reproduce**
1. Apply an Ingress `extensions/v1beta1` 
2. Scan it ! 
4. `Ingress                        kube-metriques   metriques-kube-prometheus-thanos-gateway   networking.k8s.io/v1beta1              networking.k8s.io/v1 (1.19.0)` is reported

**Expected behavior**
`Ingress                        kube-metriques   metriques-kube-prometheus-thanos-gateway   extensions/v1beta1              networking.k8s.io/v1 (1.19.0)`

**Screenshots**
NA

**Versions (please complete the following information):**
 - OS: ubuntu
 - kubent: 0.5.1
 - K8s 1.21

**Additional context**
NA

**Comment by stepanstipl** [comment]
Hi @Berber31, thanks for reporting this 👍. Can you please share:

- the original source manifest 
- and the manifest as outputted by kubectl, ie. `kubectl get ... -o yaml`

This should help me with debugging the issue (I did a quick test and wasn't able to reproduce).

Thanks

**Comment by stepanstipl** [comment]
Haven't heard back.
