### ISSUE TITLE
Link to the blog post is broken

### ISSUE THREAD

**Issue by stepanstipl** [doitintl/kube-no-trouble#272]
Link in the main readme - [Kubernetes: How to automatically detect and deal with deprecated APIs](https://blog.doit-intl.com/kubernetes-how-to-automatically-detect-and-deal-with-deprecated-apis-f9a8fc23444c) - is broken, fix.

**Comment by dark0dave** [comment]
:roll_eyes: :laughing:

**Comment by dark0dave** [comment]
Maybe we should make some github pages or something
