### ISSUE TITLE
Kubent Error - runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by Eternity022** [doitintl/kube-no-trouble#286]
Hello,

Trying to to run kubent on one of my clusters and i get the below error. 

```
5:36AM INF >>> Kube No Trouble kubent <<<
5:36AM INF version 0.5.1 (git sha a762ff3c6b5622650b86dc982652843cc2bd123c)
5:36AM INF Initializing collectors and retrieving data
5:36AM INF Target K8s version is 1.17.5
5:36AM INF Retrieved 3893 resources from collector name=Cluster
panic: runtime error: slice bounds out of range [:3] with capacity 0

goroutine 1 [running]:
helm.sh/helm/pkg/storage/driver.decodeRelease({0x0, 0xc012664a80})
	/go/pkg/mod/helm.sh/helm@v2.17.0+incompatible/pkg/storage/driver/util.go:67 +0x1b1
helm.sh/helm/pkg/storage/driver.(*ConfigMaps).List(0xc00000c678, 0x164dfd8)
	/go/pkg/mod/helm.sh/helm@v2.17.0+incompatible/pkg/storage/driver/cfgmaps.go:103 +0x2e6
helm.sh/helm/pkg/storage.(*Storage).ListDeployed(0xc0007227c0)
	/go/pkg/mod/helm.sh/helm@v2.17.0+incompatible/pkg/storage/storage.go:99 +0x50
github.com/doitintl/kube-no-trouble/pkg/collector.(*HelmV2Collector).Get(0xc00093cc30)
	/__w/kube-no-trouble/kube-no-trouble/pkg/collector/helm2.go:61 +0x6c
main.getCollectors({0xc000784ac0, 0x3, 0x0})
	/__w/kube-no-trouble/kube-no-trouble/cmd/kubent/main.go:35 +0xb9
main.main()
	/__w/kube-no-trouble/kube-no-trouble/cmd/kubent/main.go:118 +0x414
```
	
Tried multiple versions, same results. 

Same setup on all of my clusters, it works on all of my clusters except this one.

K8s version: 1.17.5

Anyone knows what is going on?

Thanks

**Comment by stepanstipl** [comment]
Hi @Eternity022,

thanks for reporting this. By the stack trace, it seems the Helm v2 driver is throwing an error when decoding a release.

Do you use Helm v2 in your cluster?

I'm not sure how much we can do about it, as we're using the latest Helm v2 version, and this seems to be an internal issue. But lets at least try to find what exactly is causing it. Can you please try to run:

```shell
kubent -l trace --helm3=false -c=false
```

This should run only Helm v2 collector with trace-level logging.

**Comment by stepanstipl** [comment]
Looks like Helm internal issue (maybe cause of old version) and we haven't heard back.
