### ISSUE TITLE
User-agent

### ISSUE THREAD

**Issue by stepanstipl** [doitintl/kube-no-trouble#325]
GKE now displays user-agent with deprecated K8S API calls [^1]; we should make sure that we set specific "kubent" user-agent header (not sure what is it at the moment), to allow for clear identification of kubent.

[^1]: https://cloud.google.com/kubernetes-engine/docs/deprecations/viewing-deprecation-insights-and-recommendations#view-deprecation-insights-recs

**Comment by stepanstipl** [comment]
Looks like we have `kubent` in user-agent, but version info is incorrectly populated (`v0.0.0`)

**Comment by dark0dave** [comment]
Fixed by #327
