### ISSUE TITLE
--version option is missing?

### ISSUE THREAD

**Issue by winterhalder** [doitintl/kube-no-trouble#334]
kubent --version option isn't actually supported <- even though it is documented.

I've installed the latest to my mac. And the --version / -v option, as documented, does not exist?
![2022-08-15_14-39-05](https://user-images.githubusercontent.com/3590310/184695812-9a2bf657-c5a5-4cd2-8636-f96ac716cfd3.png)

**Comment by dark0dave** [comment]
Will be fixed by new release. Appears you are using the old release. We will work towards getting a new release out. In the mean time please try the nightys and let us know if the issue persists.

**Comment by dark0dave** [comment]
https://github.com/doitintl/kube-no-trouble/releases/tag/nightly-0.5.1-25-g2321172
