### ISSUE TITLE
Not detecting Deprecated API CronJob

### ISSUE THREAD

**Issue by tpsimoes** [doitintl/kube-no-trouble#343]
I have a Cluster 1.21 with CronJob "apiVersion: batch/v1beta1"
and kubent it's not detecting it.

 tpsimoes  ~/cluster-ing-121  k get cj -A
No resources found
 tpsimoes  ~/cluster-ing-121  k apply -f cronjob2.yaml
Warning: batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
cronjob.batch/cron-test2 created
 tpsimoes  ~/cluster-ing-121  k get cj -A
NAMESPACE     NAME         SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
kube-system   cron-test2   */1 * * * *   False     0        <none>          6s
 tpsimoes  ~/cluster-ing-121  kubent
6:26PM INF >>> Kube No Trouble `kubent` <<<
6:26PM INF version 0.5.1 (git sha a762ff3c6b5622650b86dc982652843cc2bd123c)
6:26PM INF Initializing collectors and retrieving data
6:26PM INF Target K8s version is 1.21.9
6:26PM INF Retrieved 63 resources from collector name=Cluster
6:26PM INF Retrieved 0 resources from collector name="Helm v2"
6:26PM INF Retrieved 0 resources from collector name="Helm v3"
6:26PM INF Loaded ruleset name=custom.rego.tmpl
6:26PM INF Loaded ruleset name=deprecated-1-16.rego
6:26PM INF Loaded ruleset name=deprecated-1-22.rego
6:26PM INF Loaded ruleset name=deprecated-1-25.rego
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.22 <<<
------------------------------------------------------------------------------------------
KIND                             NAMESPACE     NAME                               API_VERSION                            REPLACE_WITH (SINCE)
Ingress                          test-ag       go-server-ingress-bkprefix         extensions/v1beta1                     networking.k8s.io/v1 (1.19.0)
Ingress                          default       test-ingress                       extensions/v1beta1                     networking.k8s.io/v1 (1.19.0)
MutatingWebhookConfiguration     <undefined>   aks-webhook-admission-controller   admissionregistration.k8s.io/v1beta1   admissionregistration.k8s.io/v1 (1.16.0)
MutatingWebhookConfiguration     <undefined>   aks-node-mutating-webhook          admissionregistration.k8s.io/v1beta1   admissionregistration.k8s.io/v1 (1.16.0)
ValidatingWebhookConfiguration   <undefined>   aks-node-validating-webhook        admissionregistration.k8s.io/v1beta1   admissionregistration.k8s.io/v1 (1.16.0)
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.25 <<<
------------------------------------------------------------------------------------------
KIND                  NAMESPACE     NAME                 API_VERSION      REPLACE_WITH (SINCE)
PodDisruptionBudget   kube-system   coredns-pdb          policy/v1beta1   policy/v1 (1.21.0)
PodDisruptionBudget   kube-system   konnectivity-agent   policy/v1beta1   policy/v1 (1.21.0)
 tpsimoes  ~/cluster-ing-121 

**Comment by stepanstipl** [comment]
Hi @tpsimoes can you please share the full manifest of the resource from the cluster? I.e. `kubectl get cj [name] -o yaml`?

**Comment by tpsimoes** [comment]
@stepanstipl 

I've got the output for the Cluster 1.20.13 - with CronJob 
(i've run with debug mode)

tvarandas@DESKTOP-DI4JEEA:~$ kubent -t 1.25.0 -l debug
3:17PM INF >>> Kube No Trouble `kubent` <<<
3:17PM INF version 0.5.1 (git sha a762ff3c6b5622650b86dc982652843cc2bd123c)
3:17PM INF Initializing collectors and retrieving data
3:17PM INF Target K8s version is 1.25.0
3:17PM DBG Retrieving: daemonsets.v1.apps
3:17PM DBG Retrieving: deployments.v1.apps
3:17PM DBG Retrieving: replicasets.v1.apps
3:17PM DBG Retrieving: statefulsets.v1.apps
3:17PM DBG Retrieving: networkpolicies.v1.networking.k8s.io
3:17PM DBG Retrieving: podsecuritypolicies.v1beta1.policy
3:17PM DBG Retrieving: ingresses.v1beta1.extensions
3:17PM DBG Retrieving: ingressclasses.v1.networking.k8s.io
3:17PM DBG Retrieving: csidrivers.v1.storage.k8s.io
3:17PM DBG Retrieving: csinodes.v1.storage.k8s.io
3:17PM DBG Retrieving: storageclasses.v1.storage.k8s.io
3:17PM DBG Retrieving: volumeattachments.v1.storage.k8s.io
3:17PM DBG Retrieving: priorityclasses.v1.scheduling.k8s.io
3:17PM DBG Retrieving: clusterroles.v1.rbac.authorization.k8s.io
3:17PM DBG Retrieving: clusterrolebindings.v1.rbac.authorization.k8s.io
3:17PM DBG Retrieving: roles.v1.rbac.authorization.k8s.io
3:17PM DBG Retrieving: rolebindings.v1.rbac.authorization.k8s.io
3:17PM DBG Retrieving: leases.v1.coordination.k8s.io
3:17PM DBG Retrieving: subjectaccessreviews.v1.authorization.k8s.io
3:17PM DBG Failed to retrieve: authorization.k8s.io/v1, Resource=subjectaccessreviews: the server does not allow this method on the requested resource
3:17PM DBG Retrieving: selfsubjectaccessreviews.v1.authorization.k8s.io
3:17PM DBG Failed to retrieve: authorization.k8s.io/v1, Resource=selfsubjectaccessreviews: the server does not allow this method on the requested resource
3:17PM DBG Retrieving: localsubjectaccessreviews.v1.authorization.k8s.io
3:17PM DBG Failed to retrieve: authorization.k8s.io/v1, Resource=localsubjectaccessreviews: the server could not find the requested resource
3:17PM DBG Retrieving: tokenreviews.v1.authentication.k8s.io
3:17PM DBG Failed to retrieve: authentication.k8s.io/v1, Resource=tokenreviews: the server does not allow this method on the requested resource
3:17PM DBG Retrieving: certificatesigningrequests.v1.certificates.k8s.io
3:17PM DBG Retrieving: apiservices.v1.apiregistration.k8s.io
3:17PM DBG Retrieving: customresourcedefinitions.v1.apiextensions.k8s.io
3:17PM DBG Retrieving: mutatingwebhookconfigurations.v1.admissionregistration.k8s.io
3:17PM DBG Retrieving: validatingwebhookconfigurations.v1.admissionregistration.k8s.io
3:17PM DBG Retrieving: runtimeclasses.v1.node.k8s.io
3:17PM DBG Retrieving: poddisruptionbudgets.v1.policy
3:17PM DBG Failed to retrieve: policy/v1, Resource=poddisruptionbudgets: the server could not find the requested resource
3:17PM DBG Retrieving: podsecuritypolicies.v1beta1.policy
3:17PM DBG Retrieving: endpointslices.v1.discovery.k8s.io
3:17PM DBG Failed to retrieve: discovery.k8s.io/v1, Resource=endpointslices: the server could not find the requested resource
3:17PM DBG Retrieving: cronjobs.v1.batch
3:17PM DBG Failed to retrieve: batch/v1, Resource=cronjobs: the server could not find the requested resource
3:17PM INF Retrieved 45 resources from collector name=Cluster
3:17PM INF Retrieved 0 resources from collector name="Helm v2"
3:17PM INF Retrieved 0 resources from collector name="Helm v3"
3:17PM INF Loaded ruleset name=custom.rego.tmpl
3:17PM INF Loaded ruleset name=deprecated-1-16.rego
3:17PM INF Loaded ruleset name=deprecated-1-22.rego
3:17PM INF Loaded ruleset name=deprecated-1-25.rego

__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.22 <<<
------------------------------------------------------------------------------------------
KIND                             NAMESPACE     NAME                                        API_VERSION                            REPLACE_WITH (SINCE)
APIService                       <undefined>   v1beta1.metrics.k8s.io                      apiregistration.k8s.io/v1beta1         apiregistration.k8s.io/v1 (1.10.0)
ClusterRole                      <undefined>   system:coredns                              rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)
ClusterRole                      <undefined>   system:azure-cloud-provider-secret-getter   rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)
ClusterRoleBinding               <undefined>   system:coredns                              rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)
ClusterRoleBinding               <undefined>   system:kube-proxy                           rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)
ClusterRoleBinding               <undefined>   metrics-server:system:auth-delegator        rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)
ClusterRoleBinding               <undefined>   system:persistent-volume-binding            rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)
MutatingWebhookConfiguration     <undefined>   aks-node-mutating-webhook                   admissionregistration.k8s.io/v1beta1   admissionregistration.k8s.io/v1 (1.16.0)
MutatingWebhookConfiguration     <undefined>   aks-webhook-admission-controller            admissionregistration.k8s.io/v1beta1   admissionregistration.k8s.io/v1 (1.16.0)
RoleBinding                      kube-system   metrics-server-auth-reader                  rbac.authorization.k8s.io/v1beta1      rbac.authorization.k8s.io/v1 (1.8.0)
ValidatingWebhookConfiguration   <undefined>   aks-node-validating-webhook                 admissionregistration.k8s.io/v1beta1   admissionregistration.k8s.io/v1 (1.16.0)




tvarandas@DESKTOP-DI4JEEA:~$ kubectl get cj -o yaml
apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"name":"hello","namespace":"default"},"spec":{"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"args":["/bin/sh","-c","date; echo Hello from the Kubernetes cluster"],"image":"busybox","name":"hello"}],"restartPolicy":"OnFailure"}}}},"schedule":"*/1 * * * *"}}
    creationTimestamp: "2022-08-31T14:14:35Z"
