### ISSUE TITLE
Ingresses are fetched using deprecated API, triggering metrics for deprecated use

### ISSUE THREAD

**Issue by liggitt** [doitintl/kube-no-trouble#364]
The cluster collector fetches ingresses using the extensions/v1beta1 API, instead of the networking.k8s.io/v1 API.

This triggers metrics and audit logs for use of deprecated APIs.

**Comment by mkassem-copado** [comment]
I also get a warning of deprecated api for `extensions/v1beta1` on GKE coming from a call from an `kubent` agent. k8s version: `1.24`

**Comment by stepanstipl** [comment]
Thanks for reporting this, this should now be fixed thanks to @liggitt . Will be immediately available in the next nightly or regular release (🤞 soon).
