### ISSUE TITLE
MacOs Install

### ISSUE THREAD

**Issue by Viox-LJ** [doitintl/kube-no-trouble#369]
Do you have some build or any way to install this on MacOs?
Thx
BR

**Comment by stepanstipl** [comment]
Hi @Viox-LJ, as documented in README[^1], the install script (`sh -c "$(curl -sSL https://git.io/install-kubent)"`) should also work on macOS, alternatively we publish and you can download build for macOS in the Releases section[^2].

I hope this answers your question :).

[^1]: https://github.com/doitintl/kube-no-trouble#install
[^2]: https://github.com/doitintl/kube-no-trouble/releases
