### ISSUE TITLE
Official Container Image

### ISSUE THREAD

**Issue by shackit** [doitintl/kube-no-trouble#377]
Hi.

Great project! Thank you.

I am keen to run kube-no-trouble in our clusters. I see a mention of an official container image in https://github.com/doitintl/kube-no-trouble/pull/302, but I am having a hard time finding it. 

Is there an official container image that I can use?

Thanks
Stephen

**Comment by dark0dave** [comment]
Thanks for your interest, we have completed the docker image work, see:
```
podman pull ghcr.io/doitintl/kube-no-trouble:nightly-0.5.1-75-g841b420
Trying to pull ghcr.io/doitintl/kube-no-trouble:nightly-0.5.1-75-g841b420...
Getting image source signatures
Copying blob 29f4a0cea2bb done  
Copying blob 788f9e204e8f done  
Copying config 04b4110ef7 done  
Writing manifest to image destination
Storing signatures
04b4110ef7eae0fa072cdac68112bdfdedecd9f6c7d487c4b102a13837be8081
```

Which is based on the latest nightly here: https://github.com/doitintl/kube-no-trouble/releases/tag/nightly-0.5.1-75-g841b420

An official release coming soon will also include it.

**Comment by shackit** [comment]
Thanks so much

**Comment by stepanstipl** [comment]
Hi @shackit the 0.6.0 is now out, you can get the docker image as `ghcr.io/doitintl/kube-no-trouble:0.6.0`, more details in [release notes](`https://github.com/doitintl/kube-no-trouble/releases/tag/0.6.0`) and some notes on usage in https://github.com/doitintl/kube-no-trouble#docker-image.

Have fun 😄 🎉

**Comment by shackit** [comment]
Wonderful news! Thank you. 

I have managed to get kubent deployed using the example in 302 but using the nightly image @dark0dave advised above, but I will happily switch this to using 0.6.0 early next week.

Thank you for all your hard work. This is really going to help my organisation with our impending round of cluster upgrades.
