### ISSUE TITLE
Give labels in output properties

### ISSUE THREAD

**Issue by mksha** [doitintl/kube-no-trouble#405]
Hi Guys,

We are using this tool to get deprecated resources but today it only give below fields in output.

Name
Namespace
Kind
ApiVersion
RuleSet
ReplaceWith
Since

I am thinking to add labels as well, so it will be easy to get to know how things are created and can be filtered further based on organization need.

**Comment by mksha** [comment]
@stepanstipl i have tried to add the new fields and it worked but its not returning the all the resources that were returns before adding new additional fields.

can you pls help me to figure out why?

**Comment by mksha** [comment]
@dark0dave @manute @liggitt @meringu @AndreasSko  pls guide me how to contribute

**Comment by stepanstipl** [comment]
Hi @mksha, thanks for the idea 👍 we will for sure consider adding this, it sounds useful.

> @stepanstipl i have tried to add the new fields and it worked but its not returning the all the resources that were returns before adding new additional fields.
>
> can you pls help me to figure out why?

As to this - I or anyone else can't help you without seeing your code 😄 . You can try to share a link to code with changes in your fork & PR against it, but I can't promise to help to guide you on how to implement this feature - it's likely a relatively large change.But hey, worth a try 😄 . Other than that, basic dev requirements are mentioned in a readme [^1], if you have some specific questions to those, let me know.

[^1]: https://github.com/doitintl/kube-no-trouble#development
