### ISSUE TITLE
when kubectl.kubernetes.io/last-applied-configuration annotation doesn't exist

### ISSUE THREAD

**Issue by SteveL1** [doitintl/kube-no-trouble#415]
Hi,

I understand that kubent will only use the last-applied-configuration annotation to evaluate if the api being used is to be deprecated.

It might be a silly question, but does that mean helm deployments, which don't have that annotation, won't be checked?

I'm assuming that it will use the apiVersion of the resource instead?

Thanks

**Comment by stepanstipl** [comment]
Hi @SteveL1, we do have a Helm v3 collector[^1] exactly for this purpose. This will collect all Helm deployments and check resources in those. And it works by checking the `apiVersion` in those asthese are renderedversions of theoriginal deployment manifests.

_(Checking apiVersion on resources in cluster is not useful, as the API version is dictated by the client [this is partially a reason why this tool exists], I've previously explained this more in detail, see[^2][^3].)_

I'm going to close this, but let me know if you have any more questions. 👍 


[^1]: https://github.com/doitintl/kube-no-trouble#:~:text=applied%2Dconfiguration%20annotation-,Helm%20v3,-%2D%20uses%20Helm%20manifests
[^2]: https://github.com/doitintl/kube-no-trouble/issues/316#issuecomment-1245335960
[^3]: https://github.com/doitintl/kube-no-trouble/issues/309#issuecomment-1235376221
