### ISSUE TITLE
list: failed to list: stream error when reading response body, may be caused by closed connection.

### ISSUE THREAD

**Issue by vbrinza** [doitintl/kube-no-trouble#428]
The majority of the times I get this error:
```
 ✗ kubent --target-version 1.25.0
5:06PM INF >>> Kube No Trouble `kubent` <<<
5:06PM INF version 0.7.0 (git sha d1bb4e5fd6550b533b2013671aa8419d923ee042)
5:06PM INF Initializing collectors and retrieving data
5:06PM INF Target K8s version is 1.25.0
5:06PM INF Retrieved 107 resources from collector name=Cluster
5:08PM ERR Failed to retrieve data from collector error="list: failed to list: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 73; INTERNAL_ERROR; received from peer" name="Helm v3"
5:08PM INF Loaded ruleset name=custom.rego.tmpl
5:08PM INF Loaded ruleset name=deprecated-1-16.rego
5:08PM INF Loaded ruleset name=deprecated-1-22.rego
5:08PM INF Loaded ruleset name=deprecated-1-25.rego
5:08PM INF Loaded ruleset name=deprecated-1-26.rego
5:08PM INF Loaded ruleset name=deprecated-future.rego
```
Only few times and only on some of the cluster I get all the deprecations.

**Comment by vbrinza** [comment]
which looks like a helm problem https://github.com/helm/helm/issues/7997

**Comment by stepanstipl** [comment]
Thank @vbrinza for reporting this 👏 It does look like the same issue as #358 (and likely https://github.com/helm/helm/issues/7997 as you already noted). I'll close this as a dupe, please follow up in #358 for updates, but let me know if you disagree.

I hope to look at #358 relatively soon, although I'm not sure yet about how much we can/should do in kubent, as it looks possibly like an issue with a specific infrastructure setup. In any case, let's continue in #358 to have it all at once place.
