### ISSUE TITLE
kubent 0.7.0 is not compatible with K8s v1.21

### ISSUE THREAD

**Issue by volkert-fastned** [doitintl/kube-no-trouble#434]
I tried this on one of our EKS clusters that is still on EKS `1.21.14-eks-ffeb93d`.

Version 0.6.0 works fine (albeit with that `groupVersion shouldn't be empty` warning reported in issue #385).

But version 0.7.0 fails on that same cluster.

I run it as follows, without any parameters:

```shell
./kubent
```

And this is the result:

```text
7:21PM INF >>> Kube No Trouble `kubent` <<<
7:21PM INF version 0.7.0 (git sha d1bb4e5fd6550b533b2013671aa8419d923ee042)
7:21PM INF Initializing collectors and retrieving data
7:21PM ERR Failed to initialize collector: <nil> error="failed to create client: exec plugin: invalid apiVersion \"client.authentication.k8s.io/v1alpha1\""
7:21PM ERR Failed to initialize collector: <nil> error="failed to create client: exec plugin: invalid apiVersion \"client.authentication.k8s.io/v1alpha1\""
7:21PM INF Loaded ruleset name=custom.rego.tmpl
7:21PM INF Loaded ruleset name=deprecated-1-16.rego
7:21PM INF Loaded ruleset name=deprecated-1-22.rego
7:21PM INF Loaded ruleset name=deprecated-1-25.rego
7:21PM INF Loaded ruleset name=deprecated-1-26.rego
7:21PM INF Loaded ruleset name=deprecated-future.rego
```

Below that, it doesn't list any deprecated API usages, even though 0.6.0 does.

I know that you can't keep supporting every old K8s version, but it would be nice to be able to run the up-to-date version of `kubent` on any cluster that is still running a supported EKS version. According to the [EKS release calendar](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar), version 1.21 should still be supported until February 15, 2023. I know it's only a month away, but until then, it's still a supported release, at least according to Amazon. :slightly_smiling_face:

Also, I couldn't find any mention of support for K8s 1.21 being discontinued in the [changelog of Release 0.7.0](https://github.com/doitintl/kube-no-trouble/releases/tag/0.7.0). It did however contained the item `Upgrade integration test versions to 1.19-1.25`, which implies that versions as far back as 1.19 should still be supported, right? Or am I misinterpreting this?

Thanks for looking into this.

**Comment by auswells** [comment]
I'm currently reviewing all of our EKS clusters, Target K8s version is 1.21.14-eks-fb459a0 with version 0.7.0 (git sha d1bb4e5fd6550b533b2013671aa8419d923ee042) and it's running fine. 

I will say when I ran the same kubent version against our GKE clusters with more resources, it took a few minutes for it to finish running so you might try letting it run for a little bit if it's not immediately returning a response. 

Hard to tell from your snippet if it exited the command or if it may still be running.

**Comment by cm3brian** [comment]
This is an issue with your awscli version and the `aws eks` generated kubeconfig and not this tooling.

**Comment by volkert-fastned** [comment]
@cm3brian Thank you, @cm3brian ! That was indeed the issue. :sweat_smile: @auswells sorry for blaming this on `kubent`. It works fine with `0.7.0`, after having updated to the latest version of AWS CLI. Closing this issue. :+1:
