### ISSUE TITLE
kubectl.kubernetes.io/last-applied-configuration annotation doesn't exist for the apps deployed using argocd

### ISSUE THREAD

**Issue by rshiva777** [doitintl/kube-no-trouble#435]
I deployed application to kuberenetes using argocd, they dont have the last applied annotation for the resource

When i run the kubent report, it is not reporting the apiversion as deprected

example: i deploy below ingress to kubernetes
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test01
  namespace: default
spec:
  rules:
  - host: nginx.test.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
```

kubectl get ing test01 -o yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: "2023-01-17T13:31:08Z"
  generation: 1
  name: test01
  namespace: default
  resourceVersion: "359731617"
  uid: 56f632b8-5d0c-46a7-9a13-19286f4561f5
spec:
  rules:
  - host: nginx.test.com
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 19.96.162.3
```

The above one when deployed dont have the annotations, so when i run the kubent, it is not showing this version as a deprecated

Similarly the applications deployed using argocd doesnt have annotations, due to which kubent is not detecting them

**Comment by rshiva777** [comment]
There is a case, when i run kubent report, and i dont see some of the deprecation apis so i upgraded the cluster. Post upgrade application was not accessible, identified that kubent did not show some of the deprecated apis in the cluster due to which the issue occured

**Comment by gurpalw** [comment]
Why don't your apps have the annotation? This sounds like it should be on the argocd issues.

I use argocd as well, and haven't encountered this issue.

**Comment by stepanstipl** [comment]
If the resources do not have the annotation (or aren't deployed via helm), `kubent` can't be expected to pick these up. Whether the annotation is added or not, and why, that's something to discuss with ArgoCD community, we can't really help here (though possibly this [^1] is relevant).

We have added support for using other annotations as well, see #323 for more details.

[^1]: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes
