### ISSUE TITLE
Feature request: Customizing ruleset

### ISSUE THREAD

**Issue by kashifest** [doitintl/kube-no-trouble#44]
It would be good to have functionalities like checking objects deployed using some specific Helm version i.e. Helm v2 which is gonna be deprecated soon and report that also. In short, allowing to incorporate custom rules also on top of K8s deprecation rules.

**Comment by stepanstipl** [comment]
Hey @kashifest, so _kubent_ will already print this information:
```
6:25PM INF Retrieved 103 resources from collector name=Cluster
6:25PM INF Retrieved 132 resources from collector name="Helm v2"
6:25PM INF Retrieved 0 resources from collector name="Helm v3"
```

It's won't appear in the json output, but maybe it can already help. As to custom rules - even if that would be possible (and it's not - I'll elaborate on that below), it wouldn't help in this scenario, as when the objects are passed to the evaluation engine, they don't contain any metadata about how they were collected.

So perhaps, if the current output is not sufficient, maybe we can modify it/enhance it to satisfy your scenario if you share more details?


@fmuyassarov no, this wouldn't really work in general, as some of the collectors have currently a [hard-coded list of objects that are collected][1]. It would probably be fine with some others, like file collector, as long as the required [response structure][2] adhered to. However, this tool was designed to check against deprecated APIs, and therefore is using some tricks to get that information that is normally not accessible (such as using the [last-applied annotation][3] or pulling configs of Helm charts), to get the original API version, as opposed to checking and passing a current object to the evaluation engine.

In general, the ability to use custom rules, with custom resources, is something that I might look at in the future, but it would require some fundamental changes. And I feel there's somewhat a conflict in those 2 use-cases: looking at how the resource was created (to detect API deprecations) vs. looking at the current state of the resource in the cluster (I assume this is more desired for other types of rules).

[1]: https://github.com/doitintl/kube-no-trouble/blob/master/pkg/collector/cluster.go#L45-L51
[2]: https://github.com/doitintl/kube-no-trouble/blob/master/rules/deprecated-1-16.rego#L5-L12
[3]: https://github.com/doitintl/kube-no-trouble/blob/master/pkg/collector/cluster.go#L63

**Comment by stepanstipl** [comment]
Do you perhaps have a specific use case in mind? And if so, would you mind sharing more details about it? I would like to better understand the motivation behind it. Thanks 👍

**Comment by kashifest** [comment]
@stepanstipl thanks a lot for the reply, and  yes we can also inform a bit more information in the output stating that these are the list of objects currently deployed through this collector and the version of the collector is going to be deprecated soon.

For the custom resource part, since this tool is already informing the k8s API deprecations smartly, what we desire on top, is for example, have a list of rules for custom resource. The custom resource might be machine if we look at [cluster-api](https://github.com/kubernetes-sigs/cluster-api/) . Since it is possible to collect all of the these resources also using kubectl for example, our wish is to provide a similar rule file you have for k8s apis, in which we will inform if there are any machine objects deployed using api version v1alpha1 for example, and we can inform that this api is going to be deprecated soon? Does it sound understandable ?

**Comment by stepanstipl** [comment]
@kashifest thanks for elaborating more on this.

Re. helm 2 - would you need this to be part of the structured (`json`/stdout) output? Or would you just adding a warning, about Helm 2 being old, be helpful?

Re. custom rules. So if I understand correctly, your scenario would still be around deprecation. I.e. you would still be interested in looking at how the resources were created (as opposed to what state are they in now), correct?

**Comment by thomas-riccardi** [comment]
+1 for custom resources deprecation (for example GKE has CRDs for managed certificates with deprecated apiVersion, cf https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs#api_versions)

**Comment by kashifest** [comment]
> @kashifest thanks for elaborating more on this.
> 
> Re. helm 2 - would you need this to be part of the structured (`json`/stdout) output? Or would you just adding a warning, about Helm 2 being old, be helpful?
> 
> Re. custom rules. So if I understand correctly, your scenario would still be around deprecation. I.e. you would still be interested in looking at how the resources were created (as opposed to what state are they in now), correct?

Sorry for the late reply. I would say for helm 2 , a warning would be enough. 

Yes, it is looking into how the resources were created.

**Comment by kashifest** [comment]
@stepanstipl any updates on this ?

**Comment by stepanstipl** [comment]
As to custom ruleset - for the reasons above, this is a bit more complicated and I'm not considering to add the ability to load custom rules in the near future.

However, to support the use case of checking for deprecation of custom resources, there might be an option that would hopefully be simpler to implement. If we would allow listing a set of resources and their versions that should be flagged, would that cover the use case you're looking for?

I imagine something like this:
```
$./kubent \
--add-resource mycustomresources.v1.example.com \
--add-resource managedcertificates.v1beta1.networking.gke.io
```
and if any found, these could be listed in "custom" section:
```
...
__________________________________________________________________________________________
>>> Custom Deprecated APIs <<<
------------------------------------------------------------------------------------------
KIND                 NAMESPACE     NAME        API_VERSION
ManagedCertificate   default       cert1       networking.gke.io/v1beta1
MyCustomResource     kube-system   test        example.com/v1
```


Would that work for you?

**Comment by thomas-riccardi** [comment]
@stepanstipl for my use-case of GKE deprecating its CDRs, yes, that would be simple and perfect: leveraging `kubent` smartness of getting raw definitions and not the currently served version by the k8s api (transparently converted).

(nit: maybe use a clearer argument name? maybe `--custom-resource`, or better: `--extra-resource` ?)

**Comment by kashifest** [comment]
> As to custom ruleset - for the reasons above, this is a bit more complicated and I'm not considering to add the ability to load custom rules in the near future.

Understood. We are planning to give it a try. If we succeed , we ll open a PR . 



> However, to support the use case of checking for deprecation of custom resources, there might be an option that would hopefully be simpler to implement. If we would allow listing a set of resources and their versions that should be flagged, would that cover the use case you're looking for?
> 
> I imagine something like this:
> 
> ```
> $./kubent \
> --add-resource mycustomresources.v1.example.com \
> --add-resource managedcertificates.v1beta1.networking.gke.io
> ```
> 
> and if any found, these could be listed in "custom" section:
> 
> ```
> ...
> __________________________________________________________________________________________
> >>> Custom Deprecated APIs <<<
> ------------------------------------------------------------------------------------------
> KIND                 NAMESPACE     NAME        API_VERSION
> ManagedCertificate   default       cert1       networking.gke.io/v1beta1
> MyCustomResource     kube-system   test        example.com/v1
> ```
> 
> Would that work for you?

That would work definitely. Thanks a lot !

**Comment by stepanstipl** [comment]
So this is out (finally 😉 ), we also cut a new [0.4.0 release](https://github.com/doitintl/kube-no-trouble/releases/tag/0.4.0). Please give it a go and let us know if it does what you need it to :). Cheers 🎉 

You can detect and flag custom resources (`-a` can be used multiple times):

```
kubent -a "ManagedCertificate.v1.networking.gke.io"
```
