### ISSUE TITLE
1.26 removal of horizontal pod autoscaler autoscaling/v2beta1 is incorrect

### ISSUE THREAD

**Issue by jack1902** [doitintl/kube-no-trouble#459]
Kubernetes removed `autoscaling/v2beta1` in kubernetes 1.25, not 1.26. In 1.26, `autoscaling/v2beta2` was removed.

1.25 `autoscaling/v2beta1` removal - https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125
1.26 `autoscaling/v2beta2` removal - https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126

Link to code within this repository: https://github.com/doitintl/kube-no-trouble/blob/4582f531c1e91fc4adf844b7b9ba6052bfa20256/pkg/rules/rego/deprecated-1-26.rego#L24

This causes a false positive when running `kubent` against a cluster which outputs `autoscaling/v2beta1` as being removed in 1.26 when in actual fact it is removed in 1.25.

**Comment by theonlysinjin** [comment]
A release with this would be appreciated. AWS is moving up their supported versions and more people would be looking at upgrading.

**Comment by flerchin** [comment]
Why did this not get released?
