### ISSUE TITLE
kubent Picks Up Resource Version in "Last Applied Configuration"

### ISSUE THREAD

**Issue by Akaame** [doitintl/kube-no-trouble#487]
Hello,

We have been using `kubent` for some time with great success. Thanks for maintaining the tool.

One problem I have been seeing is that if the `kubectl.kubernetes.io/last-applied-configuration` of a resource is populated and has a deprecated version, `kubent` still reports the said resource as a deprecated resource. 

```
kubectl get resource foo -n ns -o yaml | kubectl apply -n ns -
```

Fixes this problem as it updates the `last-applied-configuration`.

Why does `kubent` respect this particular field and would it be possible to ignore it?

Cheers.

**Comment by jrhunger** [comment]
This is the whole point of kubent.  All of the resources in the cluster are served at all available API versions.  After upgrade, resources applied with old API versions will continue to work fine.  

kubent is supposed to find ones that were last applied with an older version, meaning that if they are re-applied with the same version after upgrade to the specified k8s, then that apply will fail.

That "last applied" is a clue that something else (static yaml, CI pipeline, helm chart, etc.) is out of date and needs to be fixed.  Your "fix" above makes the kubent warning go away, but doesn't fix the source of the problem.

**Comment by bt-cj** [comment]
@Akaame  I've found that when using ArgoCD with kustomize, just changing the apiVersion doesn't trigger an update of the resource so the annotations aren't updated. Presumably it is comparing the kustomize output to the resource's apiVersion rather than the annotation.

I just started using this kubent and I, too, anticipated kubent would check the resource's apiVersion field rather than checking the annotation field.

**Comment by stepanstipl** [comment]
Hi everyone - this, and why it's not possible to tell anything by just running `kubectl get` and looking at the `apiVersion` property, has been discussed a couple of times. Please have a look at [^1] for example, where I go more in detail.

I.e. looking at the `last-applied-configuration` annotation is desirable.

If you believe this is not the case, feel free to comment why not.


I have, however, created an issue to add an FAQ section, as this is a common misconception #528.

[^1]: https://github.com/doitintl/kube-no-trouble/issues/316#issuecomment-1245335960
