### ISSUE TITLE
Tool does not respect KUBECONFIG env variable if running on a cluster

### ISSUE THREAD

**Issue by MJjainam** [doitintl/kube-no-trouble#495]
Ideally, the priority to pick target K8s version must be 
1. --kubeconfig
2. KUBECONFIG env
3. InCluster 

But in our case we are skipping KUBECONFIG env variable and directly heading to inCluster. This does not follow the standard practice in other popular tools like kubectl, kubepug etc. 

Example code from controller-runtime repo -> https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/client/config/config.go#L76

**Comment by MJjainam** [comment]
Fix for the above is in this PR -> https://github.com/doitintl/kube-no-trouble/pull/499

**Comment by dark0dave** [comment]
This was resolved in the go config.
