### ISSUE TITLE
PodSecurityPolicy Deprecation Not Detected

### ISSUE THREAD

**Issue by snelsondexcom** [doitintl/kube-no-trouble#524]
Kubent isn't detecting that `policy/v1beta1` for `PodSecurityPolicy` is deprecated in v1.21+ and unavailable in v1.25+.

Inspecting the resource via kubectl shows the following warning:
```
❯ kubectl get podsecuritypolicies
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

**Comment by snelsondexcom** [comment]
Ah, I see now that the feature is being removed entirely: https://cloud.google.com/kubernetes-engine/docs/deprecations/podsecuritypolicy

Closing this since I think it's out of the scope of what kubent is intended to do.

**Comment by stepanstipl** [comment]
I think this is potentially an issue - we should detect `policy/v1beta1` for PodSecurityPolicy as problematic.

Can you please share the full resource where this failed?
