### ISSUE TITLE
Depreciation api call triggered in the kubernetes migration notification window

### ISSUE THREAD

**Issue by antham** [doitintl/kube-no-trouble#530]
So we get that warning in the gcp console

![image](https://github.com/doitintl/kube-no-trouble/assets/4854264/82d763df-ef86-4de1-800e-01469824e83a)

And nothing from the kubent report 
```
3:08PM INF >>> Kube No Trouble `kubent` <<<
3:08PM INF version dev (git sha dev)
3:08PM INF Initializing collectors and retrieving data
3:08PM INF Target K8s version is 1.24.14-gke.2700
3:08PM INF Retrieved 27 resources from collector name=Cluster
3:08PM INF Retrieved 77 resources from collector name="Helm v3"
3:08PM INF Loaded ruleset name=custom.rego.tmpl
3:08PM INF Loaded ruleset name=deprecated-1-16.rego
3:08PM INF Loaded ruleset name=deprecated-1-22.rego
3:08PM INF Loaded ruleset name=deprecated-1-25.rego
3:08PM INF Loaded ruleset name=deprecated-1-26.rego
3:08PM INF Loaded ruleset name=deprecated-1-27.rego
3:08PM INF Loaded ruleset name=deprecated-1-29.rego
3:08PM INF Loaded ruleset name=deprecated-future.rego
```

Is it related to : 
* https://github.com/doitintl/kube-no-trouble/blob/4fa49207bb971f5578108b7c1ce4f5e9fa3f56b4/pkg/collector/cluster.go#L79 
* https://github.com/doitintl/kube-no-trouble/blob/4fa49207bb971f5578108b7c1ce4f5e9fa3f56b4/pkg/collector/cluster.go#L104
?

**Comment by seehausen** [comment]
Hi @antham 
How did you solve the problem? We still see the same warning?

**Comment by antham** [comment]
We still had the warning, we tried https://github.com/FairwindsOps/pluto and it was the same, so in the end we wrote our own tool based on the GCP API to be able to have an exact check on what's going on.
