### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by marquesj2-ppb** [doitintl/kube-no-trouble#536]
Is there a timeline for a new version to be released?

There have been a lot of bug fixes / support for newer EKS versions since 0.7.0 got released.
Doesn't need to be the 0.8.0 milestone, can be 0.7.1

**Comment by dark0dave** [comment]
We are working on it.

**Comment by dark0dave** [comment]
https://github.com/doitintl/kube-no-trouble/releases/tag/v0.7.1
