### ISSUE TITLE
Missing kubernetes 1.28 deprecations

### ISSUE THREAD

**Issue by mavendonovanhubbard** [doitintl/kube-no-trouble#595]
I'm running kubent on an intel macbook installed via homebrew. 
```
kubent --version
8:53AM INF version 0.7.2 (git sha 25eb8a3757d1db39a04e94bb97a3f099fb5c9fb6)
```

When I run against my cluster it says it's checking deprecations for a couple of different versions, but it's skipping 1.28.
```
$ kubent -t 1.28
4:13PM INF >>> Kube No Trouble `kubent` <<<
4:13PM INF version 0.7.2 (git sha 25eb8a3757d1db39a04e94bb97a3f099fb5c9fb6)
4:13PM INF Initializing collectors and retrieving data
4:13PM INF Target K8s version is 1.28.0
4:13PM INF Retrieved 601 resources from collector name=Cluster
4:13PM INF Retrieved 79 resources from collector name="Helm v3"
4:13PM INF Loaded ruleset name=custom.rego.tmpl
4:13PM INF Loaded ruleset name=deprecated-1-16.rego
4:13PM INF Loaded ruleset name=deprecated-1-22.rego
4:13PM INF Loaded ruleset name=deprecated-1-25.rego
4:13PM INF Loaded ruleset name=deprecated-1-26.rego
4:13PM INF Loaded ruleset name=deprecated-1-27.rego
4:13PM INF Loaded ruleset name=deprecated-1-29.rego
4:13PM INF Loaded ruleset name=deprecated-future.rego
```
As you can see from the above snippet, it's checking everything 1.25-1.29 except 1.28 which is the version I'm going to. Is there something different I need to do in order to update the ruleset?

**Comment by dark0dave** [comment]
We need to update the rego for 1-28. This how kubent keeps track of changes.
-> INF Loaded ruleset name=deprecated-1-28.rego

**Comment by dark0dave** [comment]
we also need 1-30

**Comment by mavendonovanhubbard** [comment]
According to this document there are no APIs being removed for 1.28 or 1.30 which is probably why there isn't a ruleset for it. https://kubernetes.io/docs/reference/using-api/deprecation-guide/
