### ISSUE TITLE
Be possible to run kubent against manifest

### ISSUE THREAD

**Issue by NargiT** [doitintl/kube-no-trouble#6]
One issue I found in kubent is that it requires to run it against the cluster, I would prefer using local manifests.

This will avoid putting credentials inside a CI/CD and be able to detect deprecated api during development or allow to prepare migration to new version not yet deployed.

I heard from @drewboswell that kubeval could provide the model.
e.x: 
```
kubent --local 1.6.1
```

**Comment by alam0rt** [comment]
would also be nice to pipe to it :)

**Comment by stepanstipl** [comment]
Thanks for suggestions, support for local files, and stdin is certainly something that can be added, I was thinking about this myself - just decided to leave out of initial implementation to simplify things.

More than happy to accept PRs ;) 🎖️ , eventually I should be able to look at this in a short while myself too.

**Comment by stepanstipl** [comment]
@NargiT support for local files has now been merged into the master via #15 :

```
$./kubent -f manifest-1.yaml -f manifest-2.json
```

A release incl. this should follow later this week (with a couple of other improvements).

@alam0rt pipe is not supported in the initial take, but I'm planning to add soon (it should be ready for it) as it totally makes sense 👍

**Comment by NargiT** [comment]
This will definitely go to our CICD for analyzing purpose. And definitly a github bot for status check in a PR. :+1:

**Comment by stepanstipl** [comment]
This has now been merged and released incl. the support for stdin input (use `-f -`). Please try the latest [0.3.0](https://github.com/doitintl/kube-no-trouble/releases/tag/0.3.0) release.
