### ISSUE TITLE
helm deployments return undefined namespaces

### ISSUE THREAD

**Issue by jbosm1** [doitintl/kube-no-trouble#67]
for some reason helm deployments seem to return namespaces as undefined

**Comment by stepanstipl** [comment]
Hi @jbosm1,

thanks for reporting the issue. I'll look into that.

Would you be able to paste here the output from kubent? Thanks.

**Comment by urmet** [comment]
I see the same thing. the deployments are created via helm2 that is controlled by gitlab kubernetes integration
```urmet@superkiisu ~ $ kubent
6:33PM INF >>> Kube No Trouble `kubent` <<<
6:33PM INF version 0.3.2 (git sha 919129b596890475965cda2b972cb6fded71f40b)
6:33PM INF Initializing collectors and retrieving data
6:33PM INF Retrieved 28 resources from collector name=Cluster
6:33PM INF Retrieved 67 resources from collector name="Helm v2"
6:33PM INF Retrieved 99 resources from collector name="Helm v3"
6:33PM INF Loaded ruleset name=deprecated-1-16.rego
6:33PM INF Loaded ruleset name=deprecated-1-22.rego
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.16  <<<
------------------------------------------------------------------------------------------
KIND         NAMESPACE     NAME                                    API_VERSION          
Deployment   <undefined>   ingress-nginx-ingress-controller        extensions/v1beta1   
Deployment   <undefined>   ingress-nginx-ingress-default-backend   extensions/v1beta1   ```

**Comment by UberKuber** [comment]
I think this occurs if the namespace wasn't specified in the metadata of the deployment.

**Comment by meringu** [comment]
Is it safe to default to the tiller namespace here?

**Comment by meringu** [comment]
Looks like we have access to the release namespace here. I'll try write up a fix tomorrow

**Comment by meringu** [comment]
^ The linked PR solves this problem in my testing.

**Comment by stepanstipl** [comment]
This should be fixed now, big thanks to @meringu  🎉 👏 for the PR, so should be part of next nightly release. 🎉

**Comment by meringu** [comment]
Hey @stepanstipl. Thanks for the merge. Any chance we could cut a 0.3.3 release?

**Comment by poornimaram88** [comment]
Hi Will there be a 0.3.3 release soon? I want to use this fix as many of my helm 2 ns are listed as undefined.

**Comment by stepanstipl** [comment]
Hi, yep, I would like to do a new release soon, trying to finish one new feature before (🤞 this week, but don't want to promise as other work tends to get in the way :)).

**Comment by meringu** [comment]
Hey @stepanstipl, I haven't seen a release yet? Would it be possible to get a 0.3.3 out while the new feature gets worked on?

**Comment by stepanstipl** [comment]
Sorry, this took a while, [0.4.0 release](https://github.com/doitintl/kube-no-trouble/releases/tag/0.4.0) is finally out, and includes this. Thanks 👍
